import MenuIcon from '@material-ui/icons/Menu';
import PlayCircleFilledIcon from '@material-ui/icons/PlayCircleFilled';
import StopIcon from '@material-ui/icons/Stop';
import CachedIcon from '@material-ui/icons/Cached';
import AddCircleOutlineIcon from '@material-ui/icons/AddCircleOutline';
import ArrowDropUpIcon from '@material-ui/icons/ArrowDropUp';
import ArrowDropDownIcon from '@material-ui/icons/ArrowDropDown';
import DeleteIcon from '@material-ui/icons/Delete';
import SaveIcon from '@material-ui/icons/Save';
import RestoreIcon from '@material-ui/icons/Restore';

export const MMenuIcon = () => (<MenuIcon />);
export const MPlayCircleFilledIcon = () => (<PlayCircleFilledIcon />);
export const MStopIcon = () => (<StopIcon />);
export const MCachedIcon = () => (<CachedIcon />);
export const MAddCircleOutlineIcon = () => (<AddCircleOutlineIcon />);
export const MArrowDropUpIcon = () => (<ArrowDropUpIcon/>);
export const MArrowDropDownIcon = () => (<ArrowDropDownIcon/>);
export const MDeleteIcon = () => (<DeleteIcon/>);
export const MSaveIcon = () => (<SaveIcon/>);
export const MRestoreIcon = () => (<RestoreIcon/>);