name: Docker Image CI - Feature Branch

on:
  push:
    branches: [feature/**]

jobs:
  build-octopus-telemetry:
    name: Build Octopus Telemetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Octopus-Telemetry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
          tags: |
            ghcr.io/${{ github.repository }}:feature