name: Docker Image CI - Fix Branch

on:
  push:
    branches: [fix/**]

jobs:
  octopus-telemetry:
    name: Build Octopus-Telemetry
    runs-on: ubuntu-latest
    env:
      TARGET_VERSION: fix
      GITHUB_REMOTE_URL: ghcr.io/${{ github.repository }}
      IMAGE_NAME: octopus-telemetry
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the docker image
        run: |
          docker build . --tag build-${TARGET_VERSION}-${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} --build-arg BUILD_DATE=$(date '  +%Y-%m-%d_%H:%M:%S')
      
      - name: Create Docker Image Tag
        run: |
          docker tag build-${TARGET_VERSION}-${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} ${GITHUB_REMOTE_URL}/${IMAGE_NAME}:${TARGET_VERSION}

      - name: Push Image to Github Packages Registry
        run: |
          docker push --all-tags ${GITHUB_REMOTE_URL}/${IMAGE_NAME}


#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and Push Octopus-Telemetry
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          cache-from: type=registry,ref=ghcr.io/sonia-auv/octopus-telemetry:fix
#          cache-to: type=inline
#          tags: |
#            ghcr.io/sonia-auv/octopus-telemetry:fix